### PR TITLE
Minor fixes to the scripts

### PR DESCRIPTION
**Pull request by mjp41**

### CODE REVIEW

**Comment by septract** [comment]
This builds and the NUnit tests all pass for me. @CaptainHayashi, what other checks are needed?

**Comment by MattWindsor91** [comment]
Does `./regress.sh` still work?  Can check myself

**Comment by septract** [comment]
Actually it's still broken for me, but not as a result of this PR. I'll file a bug.

**Comment by mjp41** [comment]
@septract does this fix it for you?

**Comment by septract** [comment]
Yes, looks like it. `test.sh` gives the correct whitespace in the list of failed tests, and I now get no output from `regress.sh`.

**Comment by MattWindsor91** [comment]
These seem to work—will merge.

**Pull request merged**
