### PR TITLE
Small changes to the main pipeline.

### PR DESCRIPTION
**Pull request by mjp41**
Refactored the front end, middle, and back end to use phase functions.

Added option to log time used in each phase.

### CODE REVIEW

**Comment by MattWindsor91** [comment]
Argh, I didn't notice this until just now :(  (I knew you'd done this, but didn't know it'd gone to PRQ!)

Should I pull this in and try to rebase my branches onto this, or wait until the big stuff is merged in and then merge this?

**Comment by septract** [comment]
Did you decide what to do with this PRQ?

**Comment by mjp41** [comment]
I was going to rebase on top of #36, once we have put that into master.

**Comment by MattWindsor91** [comment]
Is this ok to rebase and go now?

**Comment by mjp41** [comment]
It is rebased.  So if you are happy merge it.

**Comment by septract** [comment]
Builds and passes tests for me.

**Pull request merged**
